import Navbar from "./Navbar"
import Footer from "./Footer"
import Head from "next/head"

const Layout = ({children}) => {
    return (
        <div>
            <Head>
                <title>GrDe Politisches Wörterbuch</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/book.ico" />
            </Head>
            <Navbar/>
            {children}
            <Footer/>
        </div>
    )
}

export default Layout
